## pandas入门

In [2]:
#我们将使用这样得约定引入pandas
import pandas as pd
import numpy as np

### pandas的数据结构介绍
#### Series

Series是一种类似于一维数组的对象，它由一组数据（各种NumPy数据类型）以
及一组与之相关的数据标签（即索引）组成。

In [4]:
#Series的字符串表现形式为：索引在左边，值在右边。
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
#你可以通过Series 的values和index属性获取其数组表示形式和索引对象
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [6]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
#通常，我们希望所创建的Series带有一个可以对各个数据点进行标记的索引
obj2 = pd.Series([4,7,-5,3], index=('a','b','c','d'))
obj2

a    4
b    7
c   -5
d    3
dtype: int64

In [8]:
#与普通NumPy数组相比，你可以通过索引的方式选取Series中的单个或一组值
obj2['a']

4

In [11]:
obj2[['a','b','c']] #多个的话注意方括号内传入的是个一个列表

a    4
b    7
c   -5
dtype: int64

In [12]:
#根据布尔形数组进行过滤
obj2[obj2 > 0]

a    4
b    7
d    3
dtype: int64

In [13]:
#标量乘法
obj2 * 2

a     8
b    14
c   -10
d     6
dtype: int64

In [16]:
#应用数学函数
np.exp(obj2)

a      54.598150
b    1096.633158
c       0.006738
d      20.085537
dtype: float64

In [17]:
#如果数据被存放在一个Python字典中，也可以直接通过这个字典来创建Series
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [18]:
#如果只传入一个字典，则结果Series中的索引就是原字典的键（有序排列）。
#你可以传入排好序的字典的键以改变顺序
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata,index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [19]:
#我将使用缺失（missing）或NA表示缺失数据。
#pandas的isnull和notnull函数可用于检测缺失数据
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [20]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [21]:
#Series也有类似的实例方法
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

建DataFrame的办法有很多，最常用的一种是直接传入一个由等长列表或NumPy
数组组成的字典

In [22]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
frame #结果DataFrame会自动加上索引（跟Series一样），且全部列会被有序排列

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [23]:
#对于特别大的DataFrame，head方法会选取前五行
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [24]:
#如果指定了列序列，则DataFrame的列就会按照指定顺序进行排列:
pd.DataFrame(data, columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [25]:
#如果传入的列在数据中找不到，就会在结果中产生缺失值
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'], 
                      index=['one', 'two', 'three', 'four', 'five', 'six'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [26]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [29]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [30]:
#注意，返回的Series拥有原DataFrame相同的索引，且其name属性也已经被相应地设置好了
frame2['year']

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [31]:
#行也可以通过位置或名称的方式进行获取，比如用loc属性
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [32]:
#列可以通过赋值的方式进行修改
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [34]:
#将列表或数组赋值给某个列时，其长度必须跟DataFrame的长度相匹配
#如果赋值的是一个Series，就会精确匹配DataFrame的索引
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [36]:
#为不存在的列赋值会创建出一个新列
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [37]:
#del方法可以用来删除这列
del frame2['eastern']
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

注意：通过索引方式返回的列只是相应数据的视图而已，并不是副本。因此，
对返回的Series所做的任何就地修改全都会反映到源DataFrame上。通过Series
的copy方法即可指定复制列

另一种常见的数据形式是嵌套字典

In [43]:
pop = {'Nevada':{2001:2.4, 2002:2.9},
      'Ohio':{2000:1.5, 2001:1.7, 2002:3.6}}
"""如果嵌套字典传给DataFrame，pandas就会被解释为：外层字典的键作为列，内
层键则作为行索引"""
frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [40]:
#你也可以使用类似NumPy数组的方法，对DataFrame进行转置（交换行和列）
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [49]:
#如果设置了DataFrame的index和columns的name属性，则这些信息也会被显示出来
frame3.index.name = 'year'; frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [50]:
#跟Series一样，values属性也会以二维ndarray的形式返回DataFrame中的数据
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [51]:
#如果DataFrame各列的数据类型不同，则值数组的dtype就会选用能兼容所有列的数据类型
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

索引对象

In [4]:
"""pandas的索引对象负责管理轴标签和其他元数据（比如轴名称等）。构建Series
或DataFrame时，所用到的任何数组或其他序列的标签都会被转换成一个Index"""
obj = pd.Series(range(3), index=['a','b','c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [5]:
index[1:]

Index(['b', 'c'], dtype='object')

In [6]:
#Index对象是不可变的，因此用户不能对其进行修改
#不可变可以使Index对象在多个数据结构之间安全共享
labels = pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [7]:
obj2 = pd.Series([1.5,-2.5,0], index=labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [8]:
obj2.index is labels

True

#### 基本功能

重新索引

In [9]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [10]:
#pandas对象的一个重要方法是reindex，其作用是创建一个新对象，它的数据符合新的索引
#用该Series的reindex将会根据新索引进行重排。如果某个索引值当前不存在，就引入缺失值
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [11]:
"""对于时间序列这样的有序数据，重新索引时可能需要做一些插值处理。method选
项即可达到此目的，例如，使用ffill可以实现前向值填充"""
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0,2,4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [15]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [16]:
obj31 = obj3.reindex(range(6), method='ffill') #obj3是没有变化的，要赋值给新的变量
obj31

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [17]:
#借助DataFrame，reindex可以修改（行）索引和列。只传递一个序列时，会重新索引结果的行
frame = pd.DataFrame(np.arange(9).reshape(3,3), index=['a', 'c', 'd'], columns=['Ohio', 'Texas',
'California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [18]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [20]:
#列可以用columns关键字重新索引
states = ['Texas', 'Utah', 'California']
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [21]:
#丢弃某条轴上的一个或多个项很简单，只要有一个索引数组或列表即可
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [22]:
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [24]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [43]:
#对于DataFrame，可以删除任意轴上的索引值
data = pd.DataFrame(np.arange(16).reshape((4,4)), 
                    index=['Ohio', 'Colorado', 'Utah', 'NewYork'], 
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
NewYork    12   13     14    15

In [27]:
#用标签序列调用drop会从行标签（axis 0）删除值
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah       8    9     10    11
NewYork   12   13     14    15

In [28]:
#通过传递axis=1或axis='columns'可以删除列的值
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
NewYork    12     14    15

In [31]:
#许多函数，如drop，会修改Series或DataFrame的大小或形状，可以就地修改对象，不会返回新的对象
data.drop(['two', 'four'], axis='columns') #此方法和上面的方法都没有就地修改，而是返回一个新的对象

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
NewYork    12     14

In [32]:
#就地修改对象
obj.drop('c', inplace=True)
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

索引、选取和过滤

In [34]:
#Series索引（obj[...]）的工作方式类似于NumPy数组的索引，只不过Series的索引值不只是整数
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [35]:
obj['a']

0.0

In [36]:
obj[1]

1.0

In [37]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [38]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [39]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [40]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [41]:
#利用标签的切片运算与普通的Python切片运算不同，其末端是包含的
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [42]:
#用切片可以对Series的相应部分进行设置
obj['b':'c'] = 5
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [45]:
#用一个值或序列对DataFrame进行索引其实就是获取一个或多个列
data = pd.DataFrame(np.arange(16).reshape((4,4)), 
                    index=['Ohio', 'Colorado', 'Utah', 'NewYork'], 
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
NewYork    12   13     14    15

In [46]:
data['two']

Ohio         1
Colorado     5
Utah         9
NewYork     13
Name: two, dtype: int32

In [47]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
NewYork      14   12

In [55]:
#首先通过切片或布尔型数组选取数据
#选取行的语法data[:2]十分方便。向[ ]传递单一的元素或列表，就可选择列。
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [58]:
#另一种用法是通过布尔型DataFrame
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
NewYork   False  False  False  False

In [61]:
data[data < 5] = 0 #这使得DataFrame的语法与NumPy二维数组的语法很像
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
NewYork    12   13     14    15

#### 用loc和iloc进行选取

对于DataFrame的行的标签索引，我引入了特殊的标签运算符loc和iloc。

In [67]:
#它们可以让你用类似NumPy的标记，使用轴标签（loc）或整数索引（iloc）
data.loc['Colorado', ['two', 'three']] #轴标签

two      5
three    6
Name: Colorado, dtype: int32

In [64]:
#整数索引iloc
data.iloc[2, [3,0,1]]

four    11
one      8
two      9
Name: Utah, dtype: int32